hometuitionsystemapp/urls.py
from django.urls import path
from .views import *
app_name = 'hometuitionsystemapp'

urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path("login/", ClientLoginView.as_view(), name="clientlogin"),
    path("register/", ClientRegisterView.as_view(), name="clientregister"),
    path("system_admin/", AdminHomeView.as_view(), name='adminhome'),
    path("logout/", AdminLogoutView.as_view(), name="adminlogout"),
    path("system_admin/hometuitionsystem/create/",
         AdminHomeTuitionSystemCreateView.as_view(), name="adminhometuitionsystemcreate"),
    path('system_admin/hometuitionsystem/list/',
         AdminHomeTuitionSystemListView.as_view(), name="adminhometuitionsystemlist"),
    path('system_admin/<int:pk>/hometuitionsystem/detail/',
         AdminHomeTuitionSystemDetailView.as_view(), name="adminhometuitionsystemdetail"),
    path('system_admin/<int:pk>/hometuitionsystem/update/',
         AdminHomeTuitionSystemUpdateView.as_view(), name="adminhometuitionsystemupdate"),
    path('system_admin/<int:pk>/hometuitionsystem/delete/',
         AdminHomeTuitionSystemDeleteView.as_view(), name="adminhometuitionsystemdelete"),

]

hometuitionsystemproject/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hometuitionsystemapp.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hometuitionsystemapp/models.py
from django.db import models

# Create your models here.


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class HomeTuitionSystem(TimeStamp):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    contact = models.CharField(max_length=20)
    about = models.TextField()

    def __str__(self):
        return self.name


GENDER = (
    ("male", "MALE"),
    ("female", "FEMALE"),
    ("other", "OTHER"),
)


class Teacher(TimeStamp):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    gender = models.CharField(max_length=10, choices=GENDER)
    mobile = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    photo = models.ImageField(upload_to="teacher")
    education = models.CharField(max_length=50)
    slc_marksheet = models.FileField(upload_to="slc")
    plus2_transcript = models.FileField(upload_to="plus2")
    bachelor_marksheet = models.FileField(upload_to="bachelor")
    cv = models.FileField(upload_to="cv")
    about = models.TextField()

    def __str__(self):
        return self.name

hometuitionsystemapp/forms.py
from django import forms
from .models import *


class HomeTuitionSystemCreateForm(forms.ModelForm):
    class Meta:
        model = HomeTuitionSystem
        fields = "__all__"


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Enter your username..",
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Enter your password ..",
        "class": "form-control",
    }))

hometuitionsystemapp/views.py
from django.views.generic import *
from .models import *
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from .forms import *


class ClientHomeView(TemplateView):
    template_name = 'clienttemplates/home.html'


class ClientLoginView(FormView):
    template_name = "clienttemplates/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("hometuitionsystemapp:adminhome")

    def form_valid(self, form):
        uname = form.cleaned_data["username"]
        pword = form.cleaned_data["password"]
        user = authenticate(username=uname, password=pword)
        if user is not None:
            login(self.request, user)
        else:
            return render(self.request, "clienttemplates/login.html",
                          {
                              "error": "Invalid username or password", "form": form
                          })
        return super().form_valid(form)


class ClientRegisterView(TemplateView):
    template_name = "clienttemplates/register.html"


class AdminRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticted:
            return redirect("/login/")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sys'] = HomeTuitionSystem.object.first()
        return context


class AdminHomeView(TemplateView):
    template_name = 'admintemplates/adminhome.html'


class AdminLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("/")


class AdminHomeTuitionSystemCreateView(CreateView):
    template_name = "admintemplates/adminhometuitionsystemcreate.html"
    form_class = HomeTuitionSystemCreateForm
    success_url = reverse_lazy(
        "hometuitionsystemapp:adminhometuitionsystemlist")


class AdminHomeTuitionSystemListView(ListView):
    template_name = "admintemplates/adminhometuitionsystemlist.html"
    queryset = HomeTuitionSystem.objects.all()
    context_object_name = "adminhometuitionsystemlist"


class AdminHomeTuitionSystemDetailView(DetailView):
    template_name = "admintemplates/adminhometuitionsystemdetail.html"
    model = HomeTuitionSystem
    context_object_name = "adminhometuitionsystemdetail"


class AdminHomeTuitionSystemUpdateView(UpdateView):
    template_name = "admintemplates/adminhometuitionsystemcreate.html"
    form_class = HomeTuitionSystemCreateForm
    success_url = reverse_lazy(
        "hometuitionsystemapp:adminhometuitionsystemlist")
    model = HomeTuitionSystem


class AdminHomeTuitionSystemDeleteView(DeleteView):
    template_name = "admintemplates/adminhometuitionsystemdelete.html"
    success_url = reverse_lazy(
        "hometuitionsystemapp:adminhometuitionsystemlist")
    model = HomeTuitionSystem

templates/admintemplates/adminhome.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}
<h2>Admin Home</h2>
{% endblock %}

templates/admintemplates/adminhometuitionsystemcreate.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}
<h3>Create Form</h3>
<form enctype="multipart/form-data" method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
</form>
{% endblock %}

templates/admintemplates/adminhometuitionsystemdelete.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}
<h3>Delete Form</h3>
<form  method="POST">
	{% csrf_token %}
	<h2>Are you sure you want to delete?</h2>
	<button>Yes</button>	 
</form>
{% endblock %}

templates/admintemplates/adminhometuitionsystemdetail.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}
<h3>{{adminhometuitionsystemdetail.name}}</h3>
<h4>Email:{{adminhometuitionsystemdetail.email}}</h4>
<h4>Contact:{{adminhometuitionsystemdetail.contact}}</h4>
<h4>About:{{adminhometuitionsystemdetail.about}}</h4>
{% endblock %}

templates/admintemplates/adminhometuitionsystemlist.html
{% extends "admintemplates/base.html" %}
{% load static %}
{% block content %}
<h3>Home Tuition System List</h3>
<a href="{% url 'hometuitionsystemapp:adminhometuitionsystemcreate' %}">Add System</a>
<table>
	<thead>
		<tr>
			<th>Name</th>
		</tr>
	</thead>
	<tbody>
		{% for hometuitionsystem in adminhometuitionsystemlist %}
		<tr>
			<td><li><a href="{% url 'hometuitionsystemapp:adminhometuitionsystemdetail' hometuitionsystem.pk %}">{{hometuitionsystem.name}}</td></a></li>
			<td><a class="btn btn-info" href="{% url 'hometuitionsystemapp:adminhometuitionsystemupdate' hometuitionsystem.pk %}">Update</a></td>
			<td><a class="btn btn-info" href="{% url 'hometuitionsystemapp:adminhometuitionsystemdelete' hometuitionsystem.pk %}">Delete</a></td>

		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

templates/admintemplates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} {% endblock %}</title>
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	{% block css %}
	{% endblock %}
</head>
<body>
	<a href="{% url 'hometuitionsystemapp:clienthome' %}">Home</a>
	<a href="{% url 'hometuitionsystemapp:adminhome' %}">AdminHome</a>
	<a href="{% url 'hometuitionsystemapp:adminhometuitionsystemlist' %}">HomeTuitionSystemList</a>
	{% block content %}



	{% endblock %}

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	{% block js %}
	{% endblock %}

</body>
</html>

templates/clienttemplates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} {% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	{% block css %}
	{% endblock %}
</head>
<body>
	<a href="{% url 'hometuitionsystemapp:clienthome' %}">Home</a>
	<a href="{% url 'hometuitionsystemapp:adminhome' %}">AdminHome</a>
	<a href="{% url 'hometuitionsystemapp:adminhometuitionsystemlist' %}">HomeTuitionSystemList</a>
	<a href="{% url 'hometuitionsystemapp:clientlogin' %}">Login</a>
	
	{% block content %}


	{% endblock %}

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	{% block js %}
	{% endblock %}


</body>
</html>

templates/clienttemplates/home.html
{% extends "clienttemplates/base.html" %}
{% load static %}
{% block content %}
<h1>Home Tuition System</h1>
{% endblock %}

templates/clienttemplates/login.html
{% extends "clienttemplates/base.html" %}
{% load static %}
{% block content %}
<div class="login-form">
	<form action ='' method="POST">
		{% csrf_token %}
		<div>
			<p>User Name</p>
			{{form.username}}
		</div>
		<div>
			<p>Password</p>
			{{form.password}}
		</div>
		<p style="color: red">{{error}}</p>
		<label class="anim">
			<input type="checkbox" class="checkbox">
			<span>Remember me?</span>	
		</label>
		<div class="login-agileits-bottom wthree">
			<h6>
				<a href="#">Forgot password?</a>
			</h6>
		</div>
		<input type="submit" value="Login">
		<div class="register-forming">
			<p>To Register New Account -- <a href="{% url 'hometuitionsystemapp:clientregister' %}">Click Here</a></p>
		</div>
	</form>
</div>	
{% endblock %}

templates/clienttemplates/register.html
{% extends "clienttemplates/base.html" %}
{% load static %}
{% block content %}
<div class="login-form">
	<form action="", method="POST">
		<div>
			<p>User Name</p>
			<input type="text" class="name" name="user name" required="">
		</div>
		<div>
			<p>Email</p>
			<input type="email" class="email" name="email" required="">
		</div>
		<div>
			<p>Password</p>
			<input type="password" class="password" name="Password" required="">
		</div>
		<div>
			<p>Confirm Password</p>
			<input type="password" class="password" name="Password" required="">
		</div>
		<label class="anim">
			<input type="checkbox" class="checkbox">
			<span>I Accept Term & Conditions</span>
		</label>
		<input type="submit" value="Register">		
	</form>	
</div>
{% endblock %}